import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import SessionLayout from "../(common)/_components/SessionLayout";

// Use Inter instead of Geist
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <SessionLayout>{children}</SessionLayout>
      </body>
    </html>
  );
}
